In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [3]:
path = r'D:\college\sem2\Data Mining and Machine learning\Assignment_Data_mining\Forest.xlsx'

In [5]:
rawdata = pd.read_excel(path)

In [7]:
rawdata.head()

class  b1  b2  b3   b4  b5   b6   b7  b8  b9  ...  pred_minus_obs_H_b9  \
0    d   39  36  57   91  59  101   93  27  60  ...                -2.36   
1    h   84  30  57  112  51   98   92  26  62  ...                -2.26   
2    s   53  25  49   99  51   93   84  26  58  ...                -1.46   
3    s   59  26  49  103  47   92   82  25  56  ...                 2.68   
4    d   57  49  66  103  64  106  114  28  59  ...                -2.94   

   pred_minus_obs_S_b1  pred_minus_obs_S_b2  pred_minus_obs_S_b3  \
0               -18.41                -1.88                -6.43   
1               -16.27                -1.95                -6.25   
2               -15.92                -1.79                -4.64   
3               -13.77                -2.53                -6.34   
4               -21.74                -1.64                -4.62   

   pred_minus_obs_S_b4  pred_minus_obs_S_b5  pred_minus_obs_S_b6  \
0               -21.03                -1.60                -6.18   
1               -18.79                -1.99                -6.18   
2               -17.73                -0.48                -4.69   
3               -22.03                -2.34                -6.60   
4               -23.74                -0.85                -5.50   

   pred_minus_obs_S_b7  pred_minus_obs_S_b8  pred_minus_obs_S_b9  
0               -22.50                -5.20                -7.86  
1               -23.41                -8.87               -10.83  
2               -19.97                -4.10                -7.07  
3               -27.10                -7.99               -10.81  
4               -22.83                -2.74                -5.84  

[5 rows x 28 columns]

In [8]:
class_target=rawdata.iloc[:,0]

In [9]:
nrow, ncol = rawdata.shape

In [13]:
from sklearn.preprocessing import LabelEncoder

In [15]:
label_encoder = LabelEncoder()

In [16]:
rawdata['class']= label_encoder.fit_transform(rawdata['class'])

In [17]:
rawdata.head()

class  b1  b2  b3   b4  b5   b6   b7  b8  b9  ...  pred_minus_obs_H_b9  \
0      0  39  36  57   91  59  101   93  27  60  ...                -2.36   
1      1  84  30  57  112  51   98   92  26  62  ...                -2.26   
2      3  53  25  49   99  51   93   84  26  58  ...                -1.46   
3      3  59  26  49  103  47   92   82  25  56  ...                 2.68   
4      0  57  49  66  103  64  106  114  28  59  ...                -2.94   

   pred_minus_obs_S_b1  pred_minus_obs_S_b2  pred_minus_obs_S_b3  \
0               -18.41                -1.88                -6.43   
1               -16.27                -1.95                -6.25   
2               -15.92                -1.79                -4.64   
3               -13.77                -2.53                -6.34   
4               -21.74                -1.64                -4.62   

   pred_minus_obs_S_b4  pred_minus_obs_S_b5  pred_minus_obs_S_b6  \
0               -21.03                -1.60                -6.18   
1               -18.79                -1.99                -6.18   
2               -17.73                -0.48                -4.69   
3               -22.03                -2.34                -6.60   
4               -23.74                -0.85                -5.50   

   pred_minus_obs_S_b7  pred_minus_obs_S_b8  pred_minus_obs_S_b9  
0               -22.50                -5.20                -7.86  
1               -23.41                -8.87               -10.83  
2               -19.97                -4.10                -7.07  
3               -27.10                -7.99               -10.81  
4               -22.83                -2.74                -5.84  

[5 rows x 28 columns]

In [18]:
predictors=rawdata.iloc[:,1:ncol]


In [19]:
target=rawdata.iloc[:,0]

In [21]:
from sklearn.model_selection import train_test_split, cross_val_score

pred_train, pred_test, tar_train, tar_test  = train_test_split(predictors,target,test_size=.3,shuffle=False)

In [22]:
split_threshold=3

In [23]:
fpr = dict()                  # store false positive rate in a dictionary object
tpr = dict()                  # likewise, store the true positive rate

In [24]:
roc_auc = dict()

In [25]:
colors=['blue','green','red']

In [42]:
#########################################################
#----Decision Tree Classifier------
##########################################
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, auc
from sklearn.metrics import precision_score, recall_score, auc ,confusion_matrix

In [44]:
print('Below is the output for decision tree classifier')


classifier = DecisionTreeClassifier(max_depth=3)  # configure the classifier
classifier = classifier.fit(pred_train, tar_train)  # train a decision tree model
predictionsDT = classifier.predict(pred_test)  # deploy model and make predictions on test set
probDT = classifier.predict_proba(pred_test)  # obtain probability scores for each sample in test set
print("Accuracy score of our model with Decision Tree:", accuracy_score(tar_test, predictionsDT))
precision = precision_score(y_true=tar_test, y_pred=predictionsDT, average='micro')
print("Precision score of our model with Decision Tree :", precision)
recall = recall_score(y_true=tar_test, y_pred=predictionsDT, average='micro')
print("Recall score of our model with Decision Tree :", recall)

Below is the output for decision tree classifier
Accuracy score of our model with Decision Tree: 0.7961783439490446
Precision score of our model with Decision Tree : 0.7961783439490446
Recall score of our model with Decision Tree : 0.7961783439490446


In [51]:

# for x in range(3):
#     fpr[x], tpr[x], _ = roc_curve(tar_test[:], probDT[:, x], pos_label=x)
#     roc_auc[x] = auc(fpr[x], tpr[x])
#     print("AUC values of the decision tree", roc_auc[x])
#     plt.plot(fpr[x], tpr[x], color=colors[x], label='ROC curve (area = %0.2f)' % roc_auc[x])
#
# print("Accuracy score of our model with DTC :", accuracy_score(tar_test, predictions))
#plt.show()

In [50]:
#######################Multilayer Preceptron###################################
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(learning_rate='constant',activation='logistic',solver='sgd',max_iter=4000,learning_rate_init=0.001)
clf.fit(pred_train,np.ravel(tar_train,order='C'))
predictionsMLP = clf.predict(pred_test)
probMLP=clf.predict_proba(pred_test)
print("Accuracy score of our model with MLP :", accuracy_score(tar_test, predictionsMLP))
scores = cross_val_score(clf, predictors, target, cv=10)
print("Accuracy score of our model with MLP under cross validation :", scores.mean())



Accuracy score of our model with MLP : 0.8662420382165605
Accuracy score of our model with MLP under cross validation : 0.9131446509260049


In [66]:
#Confusion Matrix -

#Decision Tree
print('Confusion matrix for Decision Tree:')
cmDT=confusion_matrix(predictionsDT,tar_test)
print(cmDT)

#MLP Classifier
print('Confusion Matrix for MLP Classifier:')
cmMLP=confusion_matrix(tar_test,predictionsMLP)
print(cmMLP)

Confusion matrix for Decision Tree:
[[39  1  4  8]
 [ 0 14  0  0]
 [ 2  0 10  0]
 [ 8  8  1 62]]
Confusion Matrix for MLP Classifier:
[[43  0  5  1]
 [ 0 15  0  8]
 [ 3  0 12  0]
 [ 3  1  0 66]]


In [61]:
#######################Q2#############################################

from tabulate import tabulate
# count_d=0
# count_h=0
# print(class_target)
# for x in range(class_target.len()):
for i in range(len(pred_test)):
 print(probDT[i],probMLP[i])



[0.03225806 0.04032258 0.         0.92741935] [0.09319385 0.00513044 0.00550015 0.89617555]
[0.03225806 0.04032258 0.         0.92741935] [0.026705   0.40988723 0.01612901 0.54727876]
[0.03225806 0.04032258 0.         0.92741935] [0.05659767 0.00699311 0.00718347 0.92922576]
[0.01694915 0.         0.98305085 0.        ] [0.00979226 0.00147394 0.98718635 0.00154744]
[0.89189189 0.01801802 0.08108108 0.00900901] [0.95054714 0.00151389 0.03345238 0.01448659]
[0.03225806 0.04032258 0.         0.92741935] [0.00424976 0.00857528 0.00170578 0.98546918]
[0.03225806 0.04032258 0.         0.92741935] [0.00840756 0.01125046 0.00710372 0.97323826]
[0.         0.96363636 0.         0.03636364] [0.01096021 0.9158615  0.01204177 0.06113651]
[0.89189189 0.01801802 0.08108108 0.00900901] [0.96814421 0.00114184 0.0190931  0.01162085]
[0.03225806 0.04032258 0.         0.92741935] [0.22181091 0.0255757  0.0246179  0.72799549]
[0.89189189 0.01801802 0.08108108 0.00900901] [0.95665237 0.00510097 0.03220901 

In [64]:
proba1=[]
s1 = ['d','h','o','s']
for i in range(4):
 prob2=[s1[i],probDT[0][i],probMLP[0][i]]
 
 proba1.append(prob2)

print(tabulate(proba1, headers=['Class', 'Decision Tree Classifier','MLP Classifier']))

Class      Decision Tree Classifier    MLP Classifier
-------  --------------------------  ----------------
d                         0.0322581        0.0931939
h                         0.0403226        0.00513044
o                         0                0.00550015
s                         0.927419         0.896176


In [53]:
########################04###############################################3



def avgClassifier(pred_train,tar_train,pred_test):

 classifier = DecisionTreeClassifier(max_depth=3)  # configure the classifier
 classifier = classifier.fit(pred_train, tar_train)  # train a decision tree model
 # predictions = classifier.predict(pred_test)  # deploy model and make predictions on test set
 probDT = classifier.predict_proba(pred_test)

 clf = MLPClassifier(learning_rate='constant', activation='logistic', solver='sgd', max_iter=4000,
                     learning_rate_init=0.001)
 clf.fit(pred_train, np.ravel(tar_train, order='C'))
 # predictions1 = clf.predict(pred_test)
 probMLP = clf.predict_proba(pred_test)
 avg_predictions=[]
 avg_prob = (probDT + probMLP) / 2
 max_avg_pred=0
 for i in range(len(pred_test)):
  l=[avg_prob[i][0],avg_prob[i][1],avg_prob[i][2],avg_prob[i][3]]
  max_avg_pred=l.index(max(l))
  avg_predictions.append(max_avg_pred)
  # print(max_avg_pred,avg_prob[i])
 return avg_predictions

avg_predictions=avgClassifier(pred_train,tar_train,pred_test)
print(avg_predictions)
print('The accuracy of the Average Aggregate Classifier is:',accuracy_score(tar_test,avg_predictions))

[3, 3, 3, 2, 0, 3, 3, 1, 0, 3, 0, 0, 0, 0, 3, 0, 0, 3, 0, 2, 0, 3, 2, 3, 3, 1, 0, 2, 1, 3, 0, 0, 3, 0, 0, 3, 3, 3, 0, 3, 3, 3, 2, 2, 0, 0, 0, 0, 1, 0, 0, 3, 3, 3, 3, 1, 3, 0, 3, 3, 0, 3, 0, 0, 3, 3, 0, 0, 3, 2, 0, 0, 2, 2, 0, 3, 0, 3, 3, 0, 3, 3, 3, 0, 3, 0, 0, 0, 3, 0, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 2, 3, 0, 3, 3, 3, 3, 3, 3, 0, 0, 2, 0, 0, 1, 0, 1, 0, 3, 1, 3, 3, 3, 0, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 0, 3, 2, 3, 3, 1, 3, 3, 3, 3, 3, 1, 3, 3, 3, 0, 2, 3, 3, 3, 3]
The accuracy of the Average Aggregate Classifier is: 0.821656050955414


In [54]:
##############################Q5#####################


def conditionalClassifier(pred_train,tar_train,pred_test,tar_test):
 ##############p(a/b)=p(a&b)/p(b) then p(class=s|Dt=s)=p(class=s&DT=s)/p(DT=s)

 ###############DT#######
 classifier = DecisionTreeClassifier(max_depth=3)  # configure the classifier
 classifier = classifier.fit(pred_train, tar_train)  # train a decision tree model
 predictionsDT = classifier.predict(pred_test)  # deploy model and make predictions on test set
 probDT = classifier.predict_proba(pred_test)

 cmDT = confusion_matrix(tar_test,predictionsDT)
 condProbDT=[]
 for i in range(4):
  sumDT = 0
  for j in range(4):
   sumDT += cmDT[j][i]
  condProbDT.append(cmDT[i][i]/sumDT)


 #########################MLP########
 clf = MLPClassifier(learning_rate='constant', activation='logistic', solver='sgd', max_iter=4000,
                     learning_rate_init=0.001)
 clf.fit(pred_train, np.ravel(tar_train, order='C'))
 predictionsMLP = clf.predict(pred_test)
 probMLP = clf.predict_proba(pred_test)
 cmMLP = confusion_matrix(tar_test, predictionsMLP)
 # print(cmMLP)
 condProbMLP=[]
 for i in range(4):
  sumMLP=0
  for j in range(4):
   sumMLP+=cmMLP[j][i]
  condProbMLP.append(cmMLP[i][i]/sumMLP)
  # l=cmMLP[:][i]
  # print(cmMLP[:][i],cmMLP[i][:])
  # print("abcasdasdsa",sum(cmMLP[:][i]),sumMLP,sum(l))
 condProb=[]
 #########################Conditional Probability classifier#############
 for i in range(len(predictionsDT)):
  if(probDT[i][predictionsDT[i]]*condProbDT[predictionsDT[i]]>probMLP[i][predictionsMLP[i]]*condProbMLP[predictionsMLP[i]]):
   condProb.append(predictionsDT[i])
  else:
   condProb.append(predictionsMLP[i])

 return condProb

conditional_Predicitions=conditionalClassifier(pred_train,tar_train,pred_test,tar_test)
print(conditional_Predicitions)
print('The accuracy of the Conditional Classifier is:',accuracy_score(tar_test,conditional_Predicitions))

[3, 3, 3, 2, 0, 3, 3, 1, 0, 3, 0, 0, 0, 0, 3, 0, 0, 3, 0, 2, 0, 3, 2, 3, 3, 1, 0, 2, 1, 3, 0, 1, 3, 0, 0, 3, 3, 3, 0, 3, 3, 3, 2, 2, 0, 0, 0, 0, 1, 3, 0, 3, 3, 3, 3, 1, 3, 0, 3, 3, 3, 3, 0, 0, 3, 3, 0, 0, 3, 2, 0, 0, 2, 2, 0, 3, 0, 3, 3, 0, 3, 3, 3, 0, 3, 0, 0, 0, 3, 0, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 2, 3, 0, 3, 3, 3, 3, 3, 3, 0, 0, 2, 0, 0, 1, 0, 1, 0, 3, 1, 3, 1, 3, 0, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1, 1, 0, 3, 0, 3, 3, 1, 3, 3, 3, 3, 3, 1, 3, 1, 3, 0, 2, 3, 3, 3, 3]
The accuracy of the Conditional Classifier is: 0.8535031847133758
